/**
 * Wallet Balance Block – Save Component
 *
 * Returns null because this is a dynamic block rendered server-side via render.php.
 * The actual HTML is generated by PHP on every page load to show the current balance.
 *
 * @package woo-wallet
 */

export default function save() {
	return null;
}
